stages:
  - test

pytest:
  stage: test
  image: python:3.8
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt
  script:
    - pytest tests/
