name: Python Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If you have a requirements.txt file, uncomment the next line
        # pip install -r requirements.txt

    - name: Change to src directory and run tests with pytest
      run: |
        cd src
        pytest ../tests/
